const PUBLIC_MARKETING_COPY_REPLACEMENTS: Array<[RegExp, string]> = [
  [/Funnel Phase 6/gi, "Hành trình dùng thử"],
  [/Phase 6/gi, "Giai đoạn tối ưu"],
  [/Marketing funnel/gi, "Nguồn marketing"],
  [/decision page/gi, "trang chọn gói"],
  [/conversion path/gi, "đường đi chuyển đổi"],
  [/cognitive load/gi, "độ rối khi ra quyết định"],
  [/AI-era SaaS/gi, "phần mềm vận hành hiện đại"],
  [/AI-era positioning/gi, "định vị vận hành thông minh"],
  [/startup-style F&B operations/gi, "vận hành F&B hiện đại"],
  [/startup-level/gi, "cao cấp"],
  [/agentic/gi, "tự động hóa thông minh"],
  [/GEO readiness/gi, "Dễ tham khảo"],
  [/SEO \+ GEO/gi, "Tìm kiếm + nội dung hữu ích"],
  [/Local SEO/g, "Theo địa phương"],
  [/local SEO/g, "nội dung theo địa phương"],
  [/Programmatic SEO/g, "Mở rộng nội dung có kiểm soát"],
  [/programmatic SEO/g, "mở rộng nội dung có kiểm soát"],
  [/SEO content/gi, "nội dung tư vấn"],
  [/SEO intent/gi, "Ý định triển khai"],
  [/Nội dung SEO/gi, "Nội dung tư vấn"],
  [/SEO/gi, "tìm kiếm"],
  [/GEO/gi, "khả năng được tham khảo"],
  [/llms\.txt/gi, "tài liệu tham khảo công khai"],
  [/FAQ schema/gi, "FAQ rõ ràng"],
  [/Service schema/gi, "mô tả dịch vụ rõ ràng"],
  [/schema/gi, "dữ liệu có cấu trúc"],
  [/answer-first/gi, "trả lời thẳng vấn đề"],
  [/AI search engines/gi, "các công cụ tìm kiếm thông minh"],
  [/AI Search/g, "Tìm kiếm thông minh"],
  [/AI search/g, "tìm kiếm thông minh"],
  [/search engines/gi, "công cụ tìm kiếm"],
  [/Search engines/gi, "Công cụ tìm kiếm"],
  [/answer engine/gi, "công cụ trả lời"],
  [/internal links?/gi, "liên kết liên quan"],
  [/Internal links?/gi, "Liên kết liên quan"],
  [/topic hubs?/gi, "nhóm bài viết"],
  [/Topic hubs?/gi, "Nhóm bài viết"],
  [/thin content/gi, "nội dung mỏng"],
  [/generated/gi, "tạo tự động"]
];

export function sanitizePublicMarketingCopy(value: string) {
  return PUBLIC_MARKETING_COPY_REPLACEMENTS.reduce((copy, [pattern, replacement]) => copy.replace(pattern, replacement), value);
}
